In [1]:
import pandas as pd
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
meta_df = pd.read_csv('./dataset/meta_df.csv')

Link Dataset : [Kaggle](https://www.kaggle.com/datasets/kneroma/tacotrashdataset)

In [3]:
X = []
y = []

In [4]:
for index, row in meta_df.iterrows():
    img_path = os.path.join('./dataset/data', row['img_file'])
    
    # Membaca gambar
    img = cv2.imread(img_path)
    if img is not None:
        img = cv2.resize(img, (64, 64))
        img = img.flatten()
        
        X.append(img)
        y.append(row['cat_name'])

In [5]:
X = np.array(X)
y = np.array(y)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [7]:
datagen = ImageDataGenerator(
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

In [8]:
X_train = X_train.reshape(-1, 64, 64, 3)

In [9]:
augmented_images = []
augmented_labels = []

for img, label in zip(X_train, y_train):
    img = img.reshape((1, 64, 64, 3))  # Ubah kembali ke bentuk 4D
    for batch in datagen.flow(img, batch_size=1):
        augmented_images.append(batch[0])  # Menyimpan gambar augmentasi
        augmented_labels.append(label)  # Menyimpan label yang sesuai
        if len(augmented_images) >= 100:  # Batasi jumlah augmentasi, misalnya 100 gambar
            break

In [10]:
X_train_augmented = np.concatenate((X_train.reshape(-1, 64 * 64 * 3), np.array(augmented_images).reshape(-1, 64 * 64 * 3)), axis=0)
y_train_augmented = np.concatenate((y_train, np.array(augmented_labels)), axis=0)

In [11]:
model = svm.SVC(kernel='linear')

In [ ]:
model.fit(X_train_augmented, y_train_augmented)

In [1]:
y_pred = model.predict(X_test)

NameError: name 'model' is not defined

In [ ]:

for i in range(len(y_pred)):
    print(f"Prediksi: {y_pred[i]}, Sebenarnya: {y_test[i]}")

In [11]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  3  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  1 ...  0 41  0]
 [ 0  0  0 ...  0  0  0]]

Classification Report:
                           precision    recall  f1-score   support

                  Aerosol       0.00      0.00      0.00         2
   Aluminium blister pack       0.00      0.00      0.00         4
           Aluminium foil       0.10      0.12      0.11         8
                  Battery       0.00      0.00      0.00         1
             Broken glass       0.93      0.83      0.88        30
                Cigarette       0.43      0.72      0.54       123
     Clear plastic bottle       0.07      0.10      0.08        51
        Corrugated carton       0.62      0.40      0.48        20
             Crisp packet       0.50      0.10      0.17        10
Disposable food container       0.00      0.00      0.00         7
   Disposable plastic cup       0.13      0.15      0.14        

c:\JACKIES\Code\Python\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\JACKIES\Code\Python\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\JACKIES\Code\Python\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
